DROP TABLE USUARIO_ESTABELECIMENTO;
DROP TABLE ESTABELECIMENTO;
DROP TABLE USUARIO;
DROP TABLE TIPO_USUARIO;
DROP TABLE CATEGORIA_ESTABELECIMENTO;

CREATE TABLE TIPO_USUARIO (
IDTIPO_USUARIO NUMBER (10) NOT NULL,
NOME_TIPO_USUARIO VARCHAR2 (50) NOT NULL
);

ALTER TABLE TIPO_USUARIO ADD PRIMARY KEY ( IDTIPO_USUARIO );

CREATE TABLE USUARIO (
IDUSUARIO NUMBER (10) NOT NULL,
IDTIPO_USUARIO NUMBER (10) NOT NULL,
NOME_USUARIO VARCHAR2 (50) NOT NULL,
CIDADE_USUARIO VARCHAR2 (50) NOT NULL,
DDD_TELEFONE_USUARIO NUMBER (3) NOT NULL,
TELEFONE_USUARIO NUMBER (9) NOT NULL,
EMAIL_USUARIO VARCHAR2 (50) NOT NULL,
LOGIN_USUARIO VARCHAR2(50) NOT NULL,
SENHA_USUARIO VARCHAR2 (50) NOT NULL
);

ALTER TABLE USUARIO ADD PRIMARY KEY ( IDUSUARIO );
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_TIPO_USUARIO FOREIGN KEY ( IDTIPO_USUARIO ) REFERENCES TIPO_USUARIO ( IDTIPO_USUARIO );	

CREATE TABLE CATEGORIA_ESTABELECIMENTO (
IDCATEGORIA_ESTABELECIMENTO NUMBER (10) NOT NULL,
NOME_CATEGORIA_ESTABELECIMENTO VARCHAR2(50) NOT NULL
);

ALTER TABLE CATEGORIA_ESTABELECIMENTO ADD PRIMARY KEY ( IDCATEGORIA_ESTABELECIMENTO );

CREATE TABLE ESTABELECIMENTO (
IDESTABELECIMENTO NUMBER (10) NOT NULL,
IDCATEGORIA_ESTABELECIMENTO NUMBER (10) NOT NULL,
NOME_ESTABELECIMENTO VARCHAR2 (50) NOT NULL,
ENDERECO_ESTABELECIMENTO VARCHAR2 (50) NOT NULL,
CIDADE_ESTABELECIMENTO VARCHAR2 (50) NOT NULL,
DDD_TELEFONE_ESTABELECIMENTO NUMBER (3) NOT NULL,
TELEFONE_ESTABELECIMENTO NUMBER (9) NOT NULL,
EMAIL_ESTABELECIMENTO VARCHAR2 (50) NOT NULL,
ESTILO_ESTABELECIMENTO VARCHAR2 (50) NOT NULL,
VALOR_ESTABELECIMENTO NUMBER (10) NOT NULL
);

ALTER TABLE ESTABELECIMENTO ADD PRIMARY KEY ( IDESTABELECIMENTO );
ALTER TABLE ESTABELECIMENTO ADD CONSTRAINT FK_ESTAB_IDCAT_ESTAB FOREIGN KEY ( IDCATEGORIA_ESTABELECIMENTO ) REFERENCES CATEGORIA_ESTABELECIMENTO ( IDCATEGORIA_ESTABELECIMENTO );

CREATE TABLE USUARIO_ESTABELECIMENTO (
IDUSUARIO NUMBER (10) NOT NULL,
IDESTABELECIMENTO NUMBER (10) NOT NULL,
CRIACAO_ESTABELECIMENTO VARCHAR2 (50) NOT NULL
);

ALTER TABLE USUARIO_ESTABELECIMENTO ADD CONSTRAINT FK_USUARIO_ESTAB_ID_USUAR FOREIGN KEY ( IDUSUARIO ) REFERENCES USUARIO ( IDUSUARIO );
ALTER TABLE USUARIO_ESTABELECIMENTO ADD CONSTRAINT FK_USUARIO_ESTAB_ID_ESTAB FOREIGN KEY ( IDESTABELECIMENTO ) REFERENCES ESTABELECIMENTO ( IDESTABELECIMENTO );